CREATE DATABASE LAVE
GO

USE LAVE
GO

CREATE TABLE Medicos(
ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
CONTACTO VARCHAR(50) NOT NULL
)
GO

INSERT INTO Medicos (NOMBRE,APELLIDO,CONTACTO) VALUES ('Elmer','Vasquez','elmerr.vasquez@gmail.com'), ('Agustin','Larroca', 'agustin.larroca@gmail.com')
GO

SELECT ID, NOMBRE, APELLIDO, CONTACTO FROM MEDICOS