CREATE DATABASE LAVE
GO

USE LAVE
GO

CREATE TABLE MEDICOS(
ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
CONTACTO VARCHAR(50) NOT NULL
)
GO

CREATE TABLE ESPECIALIDADES(
ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
DESCRIPCION VARCHAR(40) NOT NULL
)
GO

INSERT INTO MEDICOS (NOMBRE,APELLIDO,CONTACTO) VALUES ('Elmer','Vasquez','elmerr.vasquez@gmail.com'), ('Agustin','Larroca', 'agustin.larroca@gmail.com'), ('Roberto', 'Gonzales','robertogonzales@gmail.com')
GO

INSERT INTO ESPECIALIDADES (DESCRIPCION) VALUES ('Odontologia'), ('Cardiologia'), ('UROLOGIA')
GO